default['openssh']['server']
default['openssh']['server']['ignore_rhosts'] = 'yes'
default['openssh']['server']['rhosts_r_s_a_authentication'] = 'no'
default['openssh']['server']['host_based_authentication'] = 'no'
default['openssh']['server']['permit_empty_passwords'] = 'no'
default['openssh']['server']['use_p_a_m'] = 'yes'
default['openssh']['server']['use_privilege_separation'] = 'yes'
default['openssh']['server']['protocol'] = '2'
default['openssh']['server']['x11_forwarding'] = 'no'
default['openssh']['server']['strict_modes'] = 'yes'
default['openssh']['server']['permit_root_login'] = 'no'
default['openssh']['server']['password_authentication'] = 'no'
default['openssh']['server']['challenge_response_authentication'] = 'no'
default['openssh']['server']['allow_tcp_forwarding'] = 'no'
default['openssh']['server']['use_privilege_separation'] = 'yes'
default['openssh']['server']['subsystem'] = 'sftp   /usr/libexec/sftp-server'
